version: '3.8'

services:
  # ----------------------------------------
  # Container 1: The Database
  # ----------------------------------------
  mysql-db:
    image: mysql:8.0.30
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: validation_service
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s

  # ----------------------------------------
  # Container 2: Your Spring Boot Backend
  # ----------------------------------------
  backend-app:
    build:
      context: ./backend        
      dockerfile: Dockerfile
    image: validation-service:v1
    container_name: spring-backend

    # =========================================================
    # 🚀 LOCAL SCALING CONFIGURATION (Uncomment to test locally)
    # To test distributed locks and concurrency locally, uncomment 
    # the 2 lines below to spin up 5 identical backend instances.
    # Note: DO NOT uncomment this on AWS Free Tier (1GB RAM limit).
    # =========================================================
    # deploy:
    #   replicas: 5

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/validation_service?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_USER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - RAZORPAY_KEY=${RAZORPAY_KEY}
      - RAZORPAY_SECRET=${RAZORPAY_SECRET}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - SECURITY_JWT_COOKIE_SECURE=false
      
      # CRITICAL FOR AWS FREE TIER: Limits Java heap memory so it doesn't starve MySQL
      - JAVA_OPTS=-Xmx300m -Xms300m
      
    depends_on:
      mysql-db:
        condition: service_healthy
    
    volumes:
      - ./aws-logs:/app/logs

  # ----------------------------------------
  # Container 3: The React Frontend (Vite + Nginx)
  # ----------------------------------------
  react-frontend:
    build:
      context: ./frontend       
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"                 # Exposes the Nginx web server to the internet
    depends_on:
      - backend-app             

volumes:
  mysql_data: