spring.application.name=validationservice

# Razorpay Configuration
razorpay.base-url=https://api.razorpay.com/v1

razorpay.auth.api-key=${RAZORPAY_KEY}
razorpay.auth.api-secret=${RAZORPAY_SECRET}
razorpay.auth.webhook-secret=${WEBHOOK_SECRET}

razorpay.validation.source-account-number=1234567890
razorpay.validation.type=optimized
razorpay.validation.endpoint=/fund_accounts/validations

#DataBase configuation
spring.datasource.url=jdbc:mysql://localhost:3306/validation_service
spring.datasource.username=venky
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect