spring.application.name=validationservice

# Razorpay Configuration
razorpay.base-url=https://api.razorpay.com
razorpay.api-key=${RAZORPAY_KEY}
razorpay.api-secret=${RAZORPAY_SECRET}
razorpay.webhook-secret=${WEBHOOK_SECRET}
razorpay.source-account-number=4564567428167673
razorpay.validation-type=optimized

# Spring security
security.jwt.secret=${JWT_SECRET}
# Expiration time
security.jwt.expiration-ms=900000
security.jwt.cookie-secure=false

#DataBase configuation
spring.datasource.url=jdbc:mysql://localhost:3306/validation_service
spring.datasource.username=venky
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
#For production I can remove them,for testing can enable this
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

#Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration



#For getting all logs this config
# TRACE level is required to see the actual parameters bound to the query
#For Testing can enable below,production not required
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
## Ensure logs go to a file for our reverse-engineering session
#logging.file.name=logs/app-trace.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# --- PRODUCTION LOGGING CONFIGURATION ---

# 1. Set the global log level to INFO (suppresses all framework debug spam)
logging.level.root=INFO

# 2. Explicitly ensure your app's package is at INFO
logging.level.com.venky.validationservice=INFO

# The active log file you are writing to right now
logging.file.name=logs/validation-service.log

#  The magic line: Create a new file every day at midnight with the date in the name
logging.logback.rollingpolicy.file-name-pattern=logs/validation-service-%d{yyyy-MM-dd}.%i.log

#  Bonus Senior line: Automatically delete logs older than 30 days so your hard drive doesn't fill up!
logging.logback.rollingpolicy.max-history=30

# 4. Define a clean, standard log pattern for both console and file
# This format is perfect for log aggregators like Datadog, Splunk, or ELK
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
